import { InteractiveScenario } from '../ScenarioEngine';
import type { ScoringRubric } from '../scoringEngine';

/** Shared rubric for all expert-difficulty scenarios. */
const EXPERT_RUBRIC: ScoringRubric = {
  passThreshold: 75,
  weights: { timing: 0.10, appropriateness: 0.30, safety: 0.40, completeness: 0.20 },
  criteria: {
    timing: { targetDurationSec: 960, toleranceSec: 120 },
    appropriateness: {
      drugRanges: [
        { drug: 'midazolam',  minDose: 0.25, maxDose: 1.5  },
        { drug: 'fentanyl',   minDose: 12.5, maxDose: 75   },
        { drug: 'propofol',   minDose: 10,   maxDose: 150  },
        { drug: 'ketamine',   minDose: 10,   maxDose: 75   },
        { drug: 'naloxone',   minDose: 0.04, maxDose: 0.4  },
        { drug: 'flumazenil', minDose: 0.1,  maxDose: 0.5  },
        { drug: 'dexmedetomidine', minDose: 0.25, maxDose: 1.5 },
      ],
    },
    safety: { spo2DangerThreshold: 88, moassMinAllowed: 1, maxDangerSeconds: 15 },
    completeness: { requiredStepFraction: 0.85 },
  },
};


export const EXPERT_PRIS: InteractiveScenario = {
  id: 'expert_pris',
  title: 'Propofol Infusion Syndrome (PRIS)',
  difficulty: 'expert',
  patientArchetype: 'hepatic',
  procedure: 'Prolonged ICU Sedation',
  description: 'ICU patient on prolonged high-dose propofol infusion develops PRIS: new-onset bradycardia, lipemia, and metabolic acidosis. Requires rapid recognition and agent switch.',
  learningObjectives: [
    'Recognize the clinical triad of PRIS',
    'Identify risk factors for PRIS',
    'Switch to alternative sedation immediately upon PRIS suspicion',
    'Manage PRIS metabolic complications',
  ],
  clinicalPearls: [
    'PRIS criteria: metabolic acidosis + at least one of: rhabdomyolysis, hepatomegaly, cardiac dysfunction, lipemia',
    'Risk factors: dose >4 mg/kg/h for >48h, low carbohydrate intake, high fat diet, catecholamine co-infusion',
    'Stop propofol immediately upon PRIS suspicion — switch to midazolam or dexmedetomidine',
    'Mortality of PRIS: 30-50% if not recognized — early diagnosis is life-saving',
  ],
  preopVignette: {
    indication: 'ICU sedation for mechanical ventilation after hepatic surgery',
    setting: 'Surgical ICU',
    history: [
      '50-year-old male, hepatic resection 2 days ago for HCC',
      'ICU day 2: propofol infusion at 5 mg/kg/h for 52 hours',
      'Underlying mild hepatic impairment (residual liver function adequate post-resection)',
      'ASA 4 perioperative. Concurrent norepinephrine for vasopressor support.',
    ],
    exam: [
      'Day 2 ICU: new bradycardia HR 44, BP 85/50',
      'Triglycerides: 890 mg/dL (lipemia — triglycerides drawn from same line)',
      'ABG: pH 7.28, PaCO2 38, HCO3 18, lactate 4.2 — metabolic acidosis with elevated lactate',
    ],
    labs: [
      'CK: 3200 U/L (elevated — rhabdomyolysis)',
      'Propofol infusion rate: 5 mg/kg/h × 52 hours',
      'ECG: new right bundle branch block pattern',
    ],
    baselineMonitors: ['Continuous ECG', 'Arterial line', 'Central venous pressure', 'SpO2'],
    targetSedationGoal: 'Switch from propofol to alternative sedation ASAP',
  },
  drugProtocols: [
    { name: 'propofol', route: 'IV infusion', typicalBolusRange: [1, 4], maxTotalDose: 400, unit: 'mg/kg/h' },
    { name: 'midazolam', route: 'IV infusion', typicalBolusRange: [0.02, 0.1], maxTotalDose: 0.2, unit: 'mg/kg/h' },
  ],
  steps: [
    {
      id: 'step_pris_recognition',
      phase: 'pre_induction',
      triggerType: 'on_start',
      millieDialogue: [
        'Day 2 ICU: propofol 5 mg/kg/h for 52 hours. New bradycardia HR 44, metabolic acidosis, triglycerides 890.',
        'What syndrome do these findings suggest?',
      ],
      question: {
        type: 'single_choice',
        prompt: 'Day 2 high-dose propofol + bradycardia + metabolic acidosis + lipemia = ?',
        options: [
          'Propofol Infusion Syndrome (PRIS)',
          'Septic shock',
          'Acute adrenal insufficiency',
          'Benzodiazepine toxicity',
        ],
        correctAnswer: 'Propofol Infusion Syndrome (PRIS)',
        feedback: {
          'Propofol Infusion Syndrome (PRIS)': 'Correct! Classic PRIS triad: high-dose prolonged propofol + new bradycardia + metabolic acidosis + lipemia.',
          'Septic shock': 'Septic shock causes vasodilation and hypotension, but the metabolic picture with lipemia strongly suggests PRIS.',
          'Acute adrenal insufficiency': "Adrenal crisis does not produce lipemia or rhabdomyolysis.",
          'Benzodiazepine toxicity': 'Patient is on propofol, not benzodiazepines — and the metabolic pattern is specific to PRIS.',
        },
      },
      simActions: [],
      teachingPoints: [
        'PRIS: dose >4 mg/kg/h AND duration >48h are the key risk factors.',
        'PRIS mechanism: propofol disrupts mitochondrial respiratory chain → impaired fat oxidation → metabolic acidosis.',
        'New ECG changes (RBBB, ST elevation in V1-V3 — "Brugada-like") are a hallmark of PRIS cardiac toxicity.',
      ],
    },
    {
      id: 'step_stop_propofol',
      phase: 'complication',
      triggerType: 'on_step_complete',
      afterStepId: 'step_pris_recognition',
      millieDialogue: [
        'PRIS confirmed. What is the SINGLE most important immediate action?',
      ],
      question: {
        type: 'single_choice',
        prompt: 'Most important immediate action for PRIS?',
        options: [
          'STOP propofol infusion immediately and switch to alternative sedation',
          'Reduce propofol to 2 mg/kg/h — acceptable dose',
          'Give sodium bicarbonate to correct acidosis, continue propofol',
          'Increase norepinephrine for the hypotension',
        ],
        correctAnswer: 'STOP propofol infusion immediately and switch to alternative sedation',
        feedback: {
          'STOP propofol infusion immediately and switch to alternative sedation': 'Correct! Stop propofol — it is the cause. Every minute of continued infusion worsens PRIS.',
          'Reduce propofol to 2 mg/kg/h — acceptable dose': 'No dose is safe once PRIS is established — stopping completely is mandatory.',
          'Give sodium bicarbonate to correct acidosis, continue propofol': 'Treating the acidosis while continuing the cause is dangerous — treat the cause first.',
          'Increase norepinephrine for the hypotension': 'Vasopressors treat the BP but not the underlying mitochondrial toxicity.',
        },
      },
      simActions: [
        { type: 'set_fio2', fio2: 1.0 },
      ],
      highlight: ['fio2-slider'],
      teachingPoints: [
        'Stop propofol IMMEDIATELY. There is no safe dose of propofol once PRIS is established.',
        'Alternative ICU sedation: midazolam infusion, dexmedetomidine, or lorazepam infusion.',
        'Continue all supportive care: vasopressors, renal replacement therapy if needed, cardiology input.',
      ],
    },
    {
      id: 'step_bradycardia_management',
      phase: 'complication',
      triggerType: 'on_physiology',
      triggerCondition: { parameter: 'hr', operator: '<', threshold: 40, durationSeconds: 20 },
      millieDialogue: [
        'HR drops to 35 bpm with BP 70/40. ECG shows new RBBB pattern.',
        'What cardiac complication of PRIS are you seeing?',
      ],
      question: {
        type: 'single_choice',
        prompt: 'New RBBB + bradycardia + hypotension in PRIS — mechanism?',
        options: [
          'PRIS cardiac toxicity: mitochondrial dysfunction → myocardial conduction failure',
          'Hyperkalemia from rhabdomyolysis causing bradycardia',
          'Propofol blocking cardiac calcium channels',
          'Vasoplegia from propofol metabolites',
        ],
        correctAnswer: 'PRIS cardiac toxicity: mitochondrial dysfunction → myocardial conduction failure',
        feedback: {
          'PRIS cardiac toxicity: mitochondrial dysfunction → myocardial conduction failure': 'Correct! PRIS disrupts myocardial mitochondria → reduced ATP → conduction system failure.',
          'Hyperkalemia from rhabdomyolysis causing bradycardia': 'Hyperkalemia is a valid concern with PRIS rhabdomyolysis but the ECG pattern of RBBB/Brugada is specific to PRIS.',
          'Propofol blocking cardiac calcium channels': 'Propofol has mild calcium channel effects but PRIS cardiac toxicity is primarily mitochondrial.',
          'Vasoplegia from propofol metabolites': 'Vasoplegia is a component but the conduction changes are primary myocardial toxicity.',
        },
      },
      simActions: [
        { type: 'set_fio2', fio2: 1.0 },
      ],
      highlight: ['hr-display', 'fio2-slider'],
      teachingPoints: [
        'PRIS cardiac pattern: new RBBB or Brugada-like ST pattern in V1-V3 is a red flag.',
        'Temporary pacing may be needed for PRIS-related complete heart block.',
        'Early ECMO referral for refractory PRIS cardiac failure — has been life-saving.',
      ],
    },
    {
      id: 'step_alternative_sedation',
      phase: 'maintenance',
      triggerType: 'on_step_complete',
      afterStepId: 'step_bradycardia_management',
      millieDialogue: [
        'Propofol stopped. Cardiologist on the way. You need to maintain ICU sedation.',
        'What alternative sedation agent is preferred in this ventilated ICU patient?',
      ],
      question: {
        type: 'single_choice',
        prompt: 'Best alternative sedation after PRIS in a mechanically ventilated ICU patient?',
        options: [
          'Dexmedetomidine infusion — cooperative, opioid-sparing, minimal respiratory depression',
          'Restart propofol at 2 mg/kg/h',
          'Ketamine infusion — dissociative, hemodynamically stable',
          'Haloperidol boluses only — no sedation infusion',
        ],
        correctAnswer: 'Dexmedetomidine infusion — cooperative, opioid-sparing, minimal respiratory depression',
        feedback: {
          'Dexmedetomidine infusion — cooperative, opioid-sparing, minimal respiratory depression': 'Correct! Dexmedetomidine is the ideal alternative — "cooperative sedation" without respiratory depression.',
          'Restart propofol at 2 mg/kg/h': 'Absolutely contraindicated — propofol caused PRIS. Never restart it in this patient.',
          'Ketamine infusion — dissociative, hemodynamically stable': 'Ketamine is an option but increases sympathetic tone and secretions — less ideal for ICU sedation.',
          'Haloperidol boluses only — no sedation infusion': 'Haloperidol alone is insufficient for a ventilated patient who needs consistent sedation.',
        },
      },
      simActions: [
        { type: 'set_fio2', fio2: 1.0 },
      ],
      highlight: ['fio2-slider'],
      teachingPoints: [
        'PRIS → switch to: midazolam infusion, dexmedetomidine, or lorazepam infusion.',
        'Dexmedetomidine allows cooperative sedation — patient can be weaned and assessed.',
        'Document PRIS as a propofol adverse reaction — avoid propofol for life.',
      ],
    },
  ],
  debrief: {
    discussionQuestions: [
      'How could PRIS have been prevented in this patient?',
      'What monitoring would you implement for any ICU patient on propofol >48 hours?',
      'What is the role of ECMO in PRIS?',
    ],
    keyTakeaways: [
      'PRIS: high-dose propofol (>4 mg/kg/h) × >48h + metabolic acidosis + lipemia + cardiac changes.',
      'Stop propofol immediately — every minute continued worsens outcomes.',
      'Monitor: daily triglycerides, CK, lactate, ECG for any patient on propofol >48h.',
      'Dexmedetomidine or midazolam as alternatives. NEVER restart propofol after PRIS.',
    ],
  },
  scoringRubric: EXPERT_RUBRIC,
};

export const EXPERT_MULTI_DRUG: InteractiveScenario = {
  id: 'expert_multi_drug',
  title: 'Multi-Drug Interaction - Synergistic Apnea',
  difficulty: 'expert',
  patientArchetype: 'elderly',
  procedure: 'Bronchoscopy',
  description: 'Elderly frail patient with COPD and CKD receives combined propofol + midazolam + fentanyl. Severe synergistic respiratory depression causes apnea. Requires multi-drug reversal strategy.',
  learningObjectives: [
    'Understand synergistic respiratory depression from opioid-hypnotic-benzodiazepine combination',
    'Know reversal agents: naloxone (opioid), flumazenil (benzodiazepine)',
    'Apply bag-mask ventilation during pharmacologic reversal',
    'Prevent future multi-drug iatrogenic apnea through dosing discipline',
  ],
  clinicalPearls: [
    'Three-drug synergy: opioid + benzo + propofol has multiplicative (not additive) respiratory depression',
    'Naloxone: 0.04 mg increments IV — titrate to respiratory effect, avoid precipitating acute pain crisis',
    'Flumazenil: 0.2 mg IV — avoid large doses if benzo-dependent (seizure risk)',
    'Frail elderly: drastically reduce ALL doses — one drug at normal dose may cause apnea',
  ],
  preopVignette: {
    indication: 'Diagnostic bronchoscopy for hemoptysis',
    setting: 'Bronchoscopy suite',
    history: [
      '78-year-old female, BMI 19 (frail), COPD GOLD stage III, CKD stage 4 (eGFR 22)',
      'Hemoptysis × 3 weeks — urgent bronchoscopy',
      'Multiple medications: LAMA/LABA, aspirin, amlodipine, furosemide',
      'ASA 4 — multiple severe systemic diseases',
    ],
    exam: [
      'Airway: Mallampati 3 — limited mouth opening from arthritis',
      'SpO2 92% on room air (COPD baseline)',
      'HR 82, BP 128/78',
    ],
    labs: ['eGFR 22 (CKD stage 4)', 'Albumin 2.8 g/dL (malnourished)'],
    baselineMonitors: ['SpO2', 'EtCO2', 'ECG', 'NIBP q3min', 'Arterial line recommended'],
    targetSedationGoal: 'Minimal sedation (MOASS 3-4) — do NOT use multi-drug combination',
  },
  drugProtocols: [
    { name: 'fentanyl', route: 'IV', typicalBolusRange: [10, 25], maxTotalDose: 50, unit: 'mcg' },
    { name: 'midazolam', route: 'IV', typicalBolusRange: [0.25, 0.5], maxTotalDose: 1, unit: 'mg' },
  ],
  steps: [
    {
      id: 'step_frailty_risk',
      phase: 'pre_induction',
      triggerType: 'on_start',
      millieDialogue: [
        'This 78-year-old frail ASA 4 patient has COPD + CKD + low albumin. The resident wants to give "standard" doses of propofol + midazolam + fentanyl.',
        'What is the most dangerous aspect of this plan?',
      ],
      question: {
        type: 'single_choice',
        prompt: 'Greatest danger of using standard multi-drug doses in this frail elderly patient?',
        options: [
          'Synergistic respiratory depression — three drugs together have multiplicative effect',
          'The drugs will not work because of renal clearance',
          'Propofol allergy risk is higher in the elderly',
          'Standard doses are fine — elderly patients are just slower to wake up',
        ],
        correctAnswer: 'Synergistic respiratory depression — three drugs together have multiplicative effect',
        feedback: {
          'Synergistic respiratory depression — three drugs together have multiplicative effect': 'Correct! Opioid + benzo + hypnotic = multiplicative, not additive, respiratory depression in frail elderly.',
          'The drugs will not work because of renal clearance': 'The opposite — CKD causes drug accumulation, making standard doses HIGHER relative exposure.',
          'Propofol allergy risk is higher in the elderly': 'True allergy to propofol is rare and not age-related.',
          'Standard doses are fine — elderly patients are just slower to wake up': 'Dangerously wrong. Standard doses can cause apnea in frail elderly patients.',
        },
      },
      simActions: [
        { type: 'set_airway_device', device: 'nasal_cannula' },
        { type: 'set_fio2', fio2: 0.40 },
      ],
      highlight: ['airway-nasal_cannula', 'fio2-slider'],
      teachingPoints: [
        'Frailty + COPD + CKD: reduce ALL drug doses by 50-70%. Use one drug at a time.',
        'Low albumin (2.8): more free drug (unbound fraction higher) — further increases effective dose.',
        'The ideal plan: topical lidocaine to airway + minimal fentanyl only, or dexmedetomidine alone.',
      ],
    },
    {
      id: 'step_apnea',
      phase: 'complication',
      triggerType: 'on_time',
      triggerTimeSeconds: 90,
      millieDialogue: [
        'Despite your warning, standard doses were given by the trainee: fentanyl 50 mcg, midazolam 2 mg, propofol 80 mg.',
        'The EtCO2 trace goes flat. SpO2 drops from 92% to 85%. RR = 0. Complete apnea.',
        'What is your FIRST action?',
      ],
      question: {
        type: 'single_choice',
        prompt: 'Complete apnea (RR 0, SpO2 dropping) — FIRST action?',
        options: [
          'BVM ventilation with 100% O2 immediately',
          'Naloxone 0.4 mg IV immediately',
          'Flumazenil 1 mg IV immediately',
          'Intubate immediately',
        ],
        correctAnswer: 'BVM ventilation with 100% O2 immediately',
        feedback: {
          'BVM ventilation with 100% O2 immediately': 'Correct! Airway and oxygenation FIRST before any pharmacologic reversal.',
          'Naloxone 0.4 mg IV immediately': 'Naloxone is appropriate next, but airway first — SpO2 is already 85% and falling.',
          'Flumazenil 1 mg IV immediately': 'Large flumazenil dose can precipitate seizures. Airway first, then titrated flumazenil.',
          'Intubate immediately': 'BVM is the first-line rescue — do not intubate before attempting BVM oxygenation.',
        },
      },
      simActions: [
        { type: 'apply_intervention', intervention: 'bag_mask' },
        { type: 'set_fio2', fio2: 1.0 },
      ],
      highlight: ['rr-display', 'fio2-slider'],
      teachingPoints: [
        'Apnea management: A-B-C first. Airway → Breathing (BVM) → Circulation.',
        'BVM can fully manage apnea while pharmacologic reversal takes effect.',
        'Never forget: drug reversal takes 1-3 minutes — BVM bridges that gap.',
      ],
    },
    {
      id: 'step_naloxone',
      phase: 'complication',
      triggerType: 'on_step_complete',
      afterStepId: 'step_apnea',
      millieDialogue: [
        'BVM ventilation is ongoing. SpO2 recovering to 94%. You want to use pharmacologic reversal.',
        'You decide to give naloxone. What is the appropriate dose strategy?',
      ],
      question: {
        type: 'single_choice',
        prompt: 'Naloxone dosing strategy for opioid component of multi-drug apnea?',
        options: [
          '0.04 mg IV increments — titrate to respiratory effect, avoid acute reversal of analgesia',
          '0.4 mg IV bolus — full dose immediately',
          '2 mg IV — maximum dose for certainty',
          'Naloxone should not be given — it will cause acute pain',
        ],
        correctAnswer: '0.04 mg IV increments — titrate to respiratory effect, avoid acute reversal of analgesia',
        feedback: {
          '0.04 mg IV increments — titrate to respiratory effect, avoid acute reversal of analgesia': 'Correct! Titrated naloxone avoids acute pain crisis, hypertension, and pulmonary edema.',
          '0.4 mg IV bolus — full dose immediately': '0.4 mg bolus causes acute pain/anxiety, hypertension, tachycardia, and can precipitate pulmonary edema.',
          '2 mg IV — maximum dose for certainty': 'Far too high — this will cause severe catecholamine storm and acute pain crisis.',
          'Naloxone should not be given — it will cause acute pain': 'Naloxone IS indicated for opioid respiratory depression — titrate carefully.',
        },
      },
      simActions: [
        { type: 'set_fio2', fio2: 0.60 },
      ],
      highlight: ['fio2-slider'],
      teachingPoints: [
        'Naloxone 0.04 mg IV every 2-3 min: titrate to spontaneous respiration, not full reversal.',
        'Full naloxone reversal causes acute pain crisis, HTN, and pulmonary edema — dangerous in elderly.',
        'Duration: naloxone 45-90 min < fentanyl redistribution — may need repeat dosing.',
      ],
    },
    {
      id: 'step_flumazenil',
      phase: 'complication',
      triggerType: 'on_step_complete',
      afterStepId: 'step_naloxone',
      millieDialogue: [
        'Naloxone helped but patient is still deeply sedated from midazolam + propofol.',
        'You consider flumazenil. What is the risk of giving flumazenil to this patient?',
      ],
      question: {
        type: 'single_choice',
        prompt: 'Key risk of flumazenil in a patient on chronic benzodiazepines or with benzodiazepine dependence?',
        options: [
          'Acute withdrawal seizures if patient is benzodiazepine-dependent',
          'Permanent reversal of sedation — patient will never sedate again',
          'Flumazenil causes cardiovascular depression',
          'No significant risks — flumazenil is universally safe',
        ],
        correctAnswer: 'Acute withdrawal seizures if patient is benzodiazepine-dependent',
        feedback: {
          'Acute withdrawal seizures if patient is benzodiazepine-dependent': 'Correct! Flumazenil can precipitate acute benzodiazepine withdrawal seizures in dependent patients.',
          'Permanent reversal of sedation — patient will never sedate again': 'Flumazenil has a short half-life (~1h) — sedation returns as it wears off.',
          'Flumazenil causes cardiovascular depression': 'Flumazenil has minimal cardiovascular effects in typical doses.',
          'No significant risks — flumazenil is universally safe': 'Seizure risk in benzodiazepine-dependent patients is a real and serious risk.',
        },
      },
      simActions: [
        { type: 'set_fio2', fio2: 0.44 },
      ],
      highlight: ['fio2-slider'],
      teachingPoints: [
        'Flumazenil 0.2 mg IV: first dose. Repeat 0.1 mg every 60 sec to max 1 mg.',
        'Avoid in: benzodiazepine-dependent patients, epilepsy, tricyclic antidepressant overdose.',
        'Short duration: 45-90 min. Resedation is common — monitor for at least 2 hours.',
      ],
    },
  ],
  debrief: {
    discussionQuestions: [
      'How would you design a sedation protocol specifically for frail elderly ASA 4 bronchoscopy patients?',
      'What monitoring would reduce the risk of iatrogenic apnea in high-risk patients?',
      'When is reversal of sedation agents appropriate vs. supportive management?',
    ],
    keyTakeaways: [
      'Three-drug synergy: multiplicative respiratory depression in frail elderly — use one drug at a time.',
      'Apnea: BVM first, then titrated naloxone (0.04 mg increments), then flumazenil (0.2 mg).',
      'Frail elderly: reduce ALL doses 50-70%. Low albumin increases free drug fraction further.',
      'Monitor for resedation after reversal — naloxone and flumazenil both shorter than drug duration.',
    ],
  },
  scoringRubric: EXPERT_RUBRIC,
};

export const EXPERT_AWARENESS: InteractiveScenario = {
  id: 'expert_awareness',
  title: 'Awareness Under Sedation - Catecholamine Surge',
  difficulty: 'expert',
  patientArchetype: 'anxious_young',
  procedure: 'Colonoscopy',
  description: 'Young woman with low drug sensitivity develops awareness under sedation during colonoscopy. Signs: purposeful movement, tachycardia, hypertension. Requires recognition, management, and medico-legal considerations.',
  learningObjectives: [
    'Recognize clinical signs of patient awareness during sedation',
    'Understand the medicolegal and psychological impact of sedation awareness',
    'Titrate supplemental sedation safely for apparent awareness',
    'Conduct a proper post-procedure debrief for a patient who may have been aware',
  ],
  clinicalPearls: [
    'Awareness incidence: 0.1-0.2% for general anesthesia, potentially higher for moderate sedation',
    'Signs: purposeful movement, tachycardia, hypertension, sweating, grimacing',
    'Drug resistance: young fit patients (especially females) may need higher doses than standard',
    'Post-procedure: always tell patients what happened — concealment worsens psychological harm',
  ],
  preopVignette: {
    indication: 'Screening colonoscopy',
    setting: 'Ambulatory endoscopy suite',
    history: [
      '35-year-old female, athletic, ASA 1',
      'Low drug sensitivity (reported needing more anesthesia for prior dental procedures)',
      'No regular medications, NKDA',
      'BMI 21 — no obesity',
    ],
    exam: [
      'Airway: Mallampati 1',
      'HR 68, BP 112/72, SpO2 99%',
      'Very fit — reduced adipose tissue (smaller volume of distribution for lipophilic drugs)',
    ],
    baselineMonitors: ['SpO2', 'EtCO2', 'NIBP q5min', 'ECG'],
    targetSedationGoal: 'MOASS 2-3 — may require higher than standard doses',
  },
  drugProtocols: [
    { name: 'propofol', route: 'IV', typicalBolusRange: [60, 120], maxTotalDose: 300, unit: 'mg' },
    { name: 'fentanyl', route: 'IV', typicalBolusRange: [50, 100], maxTotalDose: 200, unit: 'mcg' },
    { name: 'midazolam', route: 'IV', typicalBolusRange: [1, 2], maxTotalDose: 6, unit: 'mg' },
  ],
  steps: [
    {
      id: 'step_drug_resistance',
      phase: 'pre_induction',
      triggerType: 'on_start',
      millieDialogue: [
        "This patient mentions she needed 'extra' anesthesia for a previous dental procedure.",
        'What factor most likely explains lower sensitivity to sedative agents in this patient?',
      ],
      question: {
        type: 'single_choice',
        prompt: 'Most likely reason for reduced sedative drug sensitivity in a fit young female?',
        options: [
          'Pharmacodynamic variability — reduced GABA-A receptor sensitivity',
          'She is making it up',
          'Higher hepatic metabolism from regular exercise',
          'Larger blood volume diluting the drugs',
        ],
        correctAnswer: 'Pharmacodynamic variability — reduced GABA-A receptor sensitivity',
        feedback: {
          'Pharmacodynamic variability — reduced GABA-A receptor sensitivity': 'Correct! GABA-A receptor subunit polymorphisms cause true pharmacodynamic variability in drug sensitivity.',
          'She is making it up': 'Never dismiss patient-reported drug sensitivity — it is a real and documented phenomenon.',
          'Higher hepatic metabolism from regular exercise': 'Exercise affects some drugs but GABA sensitivity is a receptor-level pharmacodynamic difference.',
          'Larger blood volume diluting the drugs': 'Blood volume differences are small and do not explain significant drug resistance.',
        },
      },
      simActions: [
        { type: 'set_airway_device', device: 'nasal_cannula' },
        { type: 'set_fio2', fio2: 0.29 },
      ],
      highlight: ['airway-nasal_cannula', 'fio2-slider'],
      teachingPoints: [
        'Drug sensitivity varies 10-fold between individuals for the same drug.',
        'Document "requires higher sedation doses" in the chart — guides future anesthesia providers.',
        'Consider EEG-guided sedation (BIS monitor) for patients with known drug resistance.',
      ],
    },
    {
      id: 'step_awareness_signs',
      phase: 'complication',
      triggerType: 'on_time',
      triggerTimeSeconds: 180,
      millieDialogue: [
        'Mid-procedure: patient suddenly reaches toward the scope, HR spikes to 118, BP 158/94.',
        'She appears to be grimacing. What does this clinical picture suggest?',
      ],
      question: {
        type: 'single_choice',
        prompt: 'Purposeful movement + tachycardia + hypertension during sedation = ?',
        options: [
          'Patient awareness — catecholamine surge from consciousness',
          'Vasovagal episode',
          'Paradoxical benzodiazepine reaction',
          'Normal movement during sedation — ignore',
        ],
        correctAnswer: 'Patient awareness — catecholamine surge from consciousness',
        feedback: {
          'Patient awareness — catecholamine surge from consciousness': 'Correct! Purposeful movement + sympathetic activation = classic awareness picture.',
          'Vasovagal episode': 'Vasovagal causes bradycardia and hypotension — opposite of this picture.',
          'Paradoxical benzodiazepine reaction': 'Paradoxical reaction is agitation after benzodiazepine without purposeful goal-directed movement.',
          'Normal movement during sedation — ignore': 'Purposeful (goal-directed) movement is never normal — it indicates inadequate depth.',
        },
      },
      simActions: [
        { type: 'administer_drug', drug: 'midazolam', dose: 1 },
        { type: 'administer_drug', drug: 'propofol', dose: 40 },
        { type: 'advance_time', seconds: 60 },
      ],
      highlight: ['midazolam-1', 'propofol-50'],
      teachingPoints: [
        'Awareness signs: purposeful movement, tachycardia, hypertension, sweating, eye opening, grimacing.',
        'Immediate response: supplemental propofol + midazolam. Verify IV patency — disconnected IV is a common cause.',
        'Ask patient later: "Do you recall anything from the procedure?" — disclosure obligation.',
      ],
    },
    {
      id: 'step_iv_patency',
      phase: 'complication',
      triggerType: 'on_step_complete',
      afterStepId: 'step_awareness_signs',
      millieDialogue: [
        'You gave more propofol but the patient is still moving. You notice the IV site looks swollen.',
        'What has likely happened?',
      ],
      question: {
        type: 'single_choice',
        prompt: 'IV site is swollen, drugs not working — most likely explanation?',
        options: [
          'IV infiltration — drugs are going subcutaneously, not IV',
          'Complete drug resistance — this patient cannot be sedated',
          'Allergic reaction to propofol',
          'The drugs need more time — just wait',
        ],
        correctAnswer: 'IV infiltration — drugs are going subcutaneously, not IV',
        feedback: {
          'IV infiltration — drugs are going subcutaneously, not IV': 'Correct! Swollen IV site = infiltration. Drugs are not reaching systemic circulation.',
          'Complete drug resistance — this patient cannot be sedated': 'Drug resistance exists but does not cause complete treatment failure — check IV first.',
          'Allergic reaction to propofol': 'Allergic reaction presents with hives, hypotension, bronchospasm — not infiltration.',
          'The drugs need more time — just wait': 'Never wait when IV site is swollen and drugs are not working — check IV patency immediately.',
        },
      },
      simActions: [
        { type: 'administer_drug', drug: 'fentanyl', dose: 50 },
        { type: 'administer_drug', drug: 'propofol', dose: 60 },
        { type: 'advance_time', seconds: 90 },
      ],
      highlight: ['fentanyl-50', 'propofol-50'],
      teachingPoints: [
        'IV patency: check at every bolus. Swelling, pain, or coolness at site = infiltration.',
        'Restart IV in new site before proceeding — drug delivery is the first troubleshooting step for awareness.',
        'Ensure you confirm blood flashback before giving any drug.',
      ],
    },
    {
      id: 'step_postprocedure_disclosure',
      phase: 'recovery',
      triggerType: 'on_time',
      triggerTimeSeconds: 480,
      millieDialogue: [
        'Procedure complete with new IV site and higher doses. Patient is now fully awake.',
        'She says "I think I remember something — it was like a dream." How do you respond?',
      ],
      question: {
        type: 'single_choice',
        prompt: 'Patient reports possible awareness recall — how do you respond?',
        options: [
          'Acknowledge her experience, document it, offer a full honest explanation and psychological support',
          'Tell her it was just a dream — sedation always works',
          'Say nothing and document nothing',
          'Tell her the drugs were given correctly — she must be wrong',
        ],
        correctAnswer: 'Acknowledge her experience, document it, offer a full honest explanation and psychological support',
        feedback: {
          'Acknowledge her experience, document it, offer a full honest explanation and psychological support': 'Correct! Duty of candor: disclose, document, support. This is both ethical and legally required.',
          'Tell her it was just a dream — sedation always works': 'Dismissing awareness can cause significant psychological harm and undermines trust.',
          'Say nothing and document nothing': 'Concealment of adverse events is unethical and potentially illegal.',
          'Tell her the drugs were given correctly — she must be wrong': 'Defensive response — invalidates patient experience and damages trust.',
        },
      },
      simActions: [],
      teachingPoints: [
        'Duty of candor: obligatory disclosure of any adverse event including awareness.',
        'Awareness post-sedation: document full details, offer psychological referral.',
        'PTSD can develop after awareness events — early psychological support reduces this risk.',
        'Note: "patient reports possible procedural recall — IV infiltration identified and corrected" in the chart.',
      ],
    },
  ],
  debrief: {
    discussionQuestions: [
      'What preoperative steps could have predicted this patient\'s drug resistance?',
      'How does the medico-legal concept of "duty of candor" apply to awareness events?',
      'What changes would you make to your sedation technique for future cases with this patient?',
    ],
    keyTakeaways: [
      'Always verify IV patency before each drug bolus — infiltration is a common cause of awareness.',
      'Document patient-reported drug sensitivity and use higher starting doses for next procedure.',
      'Awareness events require honest disclosure, documentation, and psychological follow-up.',
      'Consider BIS monitoring for patients with known sedation resistance.',
    ],
  },
  scoringRubric: EXPERT_RUBRIC,
};

export const EXPERT_MALIGNANT_HYPERTHERMIA: InteractiveScenario = {
  id: 'expert_malignant_hyperthermia',
  title: 'Malignant Hyperthermia Mimic - Ketamine & Dental',
  difficulty: 'expert',
  patientArchetype: 'hcm_young',
  procedure: 'Complex Dental Surgery with Ketamine Sedation',
  description: 'Young male with unknown RYR1 mutation develops hyperthermia, tachycardia, and rigidity during ketamine sedation. The MH-like picture requires differential diagnosis and urgent dantrolene.',
  learningObjectives: [
    'Recognize the clinical features of malignant hyperthermia',
    'Perform rapid MH differential diagnosis (serotonin syndrome, neuroleptic malignant syndrome, heat stroke)',
    'Initiate the MH crisis protocol including dantrolene dosing',
    'Understand why ketamine can occasionally trigger MH in susceptible individuals',
  ],
  clinicalPearls: [
    'MH triad: hyperthermia + muscle rigidity + tachycardia after triggering agent',
    'Triggering agents: volatile anesthetics (halothane, sevoflurane), succinylcholine. Ketamine: rare trigger.',
    'Dantrolene 2.5 mg/kg IV: inhibits ryanodine receptor → prevents SR Ca2+ release',
    'MH hotline: 1-800-MH-HYPER — contact for real-time expert guidance',
  ],
  preopVignette: {
    indication: 'Complex third molar surgery — bone impaction, multiple extractions',
    setting: 'Oral surgery suite',
    history: [
      '22-year-old male, previously healthy, no known drug reactions',
      'ASA 1 — no prior anesthesia. Family history unknown (adopted).',
      'No medications, NKDA',
      'Has had muscle cramps with vigorous exercise (not investigated)',
    ],
    exam: [
      'Airway: Mallampati 1, excellent mouth opening',
      'HR 72, BP 118/72, SpO2 99%',
      'Athletic build, well-muscled',
    ],
    baselineMonitors: ['Continuous ECG', 'SpO2', 'EtCO2', 'Core temperature probe', 'NIBP q3min'],
    targetSedationGoal: 'MOASS 1-2 for complex dental surgery',
  },
  drugProtocols: [
    { name: 'ketamine', route: 'IV', typicalBolusRange: [1, 2], maxTotalDose: 200, unit: 'mg' },
    { name: 'midazolam', route: 'IV', typicalBolusRange: [1, 2], maxTotalDose: 4, unit: 'mg' },
    { name: 'propofol', route: 'IV', typicalBolusRange: [40, 80], maxTotalDose: 200, unit: 'mg' },
  ],
  steps: [
    {
      id: 'step_mh_history',
      phase: 'pre_induction',
      triggerType: 'on_start',
      millieDialogue: [
        "This young man mentions exercise-induced muscle cramps but never had anesthesia. Family history is unknown.",
        'What pre-anesthesia screening question would reveal MH susceptibility risk?',
      ],
      question: {
        type: 'single_choice',
        prompt: 'Best screening question for MH susceptibility?',
        options: [
          '"Has anyone in your biological family had an unusual reaction to anesthesia (high fever, muscle stiffness)?"',
          '"Do you have any drug allergies?"',
          '"Have you ever fainted?"',
          '"Do you exercise regularly?"',
        ],
        correctAnswer: '"Has anyone in your biological family had an unusual reaction to anesthesia (high fever, muscle stiffness)?"',
        feedback: {
          '"Has anyone in your biological family had an unusual reaction to anesthesia (high fever, muscle stiffness)?"': 'Correct! Family history of MH or unexplained perioperative death is the key screening question.',
          '"Do you have any drug allergies?"': 'MH is not an allergy — it is a pharmacogenomic susceptibility.',
          '"Have you ever fainted?"': 'Fainting is not related to MH.',
          '"Do you exercise regularly?"': 'Exercise-induced muscle cramps can be a sign of RYR1 mutation but is not the specific MH screening question.',
        },
      },
      simActions: [
        { type: 'set_airway_device', device: 'nasal_cannula' },
        { type: 'set_fio2', fio2: 0.35 },
        { type: 'administer_drug', drug: 'midazolam', dose: 2 },
        { type: 'administer_drug', drug: 'ketamine', dose: 80 },
        { type: 'advance_time', seconds: 120 },
      ],
      highlight: ['airway-nasal_cannula', 'fio2-slider', 'midazolam-2', 'ketamine-100'],
      teachingPoints: [
        'MH susceptibility: autosomal dominant RYR1 mutations in 70% of cases.',
        'Adopted patients or unknown family history = proceed with caution, have dantrolene available.',
        'MH-safe technique: propofol + opioid. Avoid: volatile agents, succinylcholine.',
      ],
    },
    {
      id: 'step_mh_recognition',
      phase: 'complication',
      triggerType: 'on_time',
      triggerTimeSeconds: 180,
      millieDialogue: [
        '20 minutes in: HR is 145, temperature 39.8°C (rising fast), jaw is stiff (trismus), EtCO2 is 68.',
        'This is not emergence agitation. What is happening?',
      ],
      question: {
        type: 'single_choice',
        prompt: 'Tachycardia + rising temperature + trismus + high EtCO2 — most likely diagnosis?',
        options: [
          'Malignant hyperthermia — activate MH protocol immediately',
          'Ketamine emergence reaction',
          'Neuroleptic malignant syndrome',
          'Serotonin syndrome',
        ],
        correctAnswer: 'Malignant hyperthermia — activate MH protocol immediately',
        feedback: {
          'Malignant hyperthermia — activate MH protocol immediately': 'Correct! Trismus (masseter spasm) + rising temperature + tachycardia + elevated EtCO2 = MH until proven otherwise.',
          'Ketamine emergence reaction': 'Emergence is confusion/agitation — not hyperthermia, muscle rigidity, and rising CO2.',
          'Neuroleptic malignant syndrome': 'NMS requires prior antipsychotic exposure and takes days to develop — not this acute.',
          'Serotonin syndrome': 'Serotonin syndrome requires serotonergic drug exposure — this patient has none.',
        },
      },
      simActions: [
        { type: 'set_fio2', fio2: 1.0 },
        { type: 'apply_intervention', intervention: 'bag_mask' },
      ],
      highlight: ['fio2-slider'],
      teachingPoints: [
        'MH clinical criteria (Larach score): temperature rise ≥1.5°C/hr, masseter spasm, EtCO2 >55 despite adequate ventilation.',
        'CALL for help immediately — MH crisis requires a team response.',
        'Stop any triggering agent immediately.',
      ],
    },
    {
      id: 'step_dantrolene',
      phase: 'complication',
      triggerType: 'on_step_complete',
      afterStepId: 'step_mh_recognition',
      millieDialogue: [
        'MH protocol activated. What is the correct initial dantrolene dose for this 80 kg patient?',
      ],
      question: {
        type: 'numeric_range',
        prompt: 'Dantrolene initial IV bolus in mg for MH (2.5 mg/kg × 80 kg)',
        correctAnswer: 200,
        idealRange: [160, 240],
        feedback: {
          low: 'Below 160 mg is underdosing — 2.5 mg/kg is the minimum initial dose.',
          ideal: '2.5 mg/kg (200 mg) is the correct initial dose. Can repeat every 5 minutes to max 10 mg/kg.',
          high: 'Above 240 mg as initial dose is higher than recommended starting dose.',
        },
      },
      simActions: [
        { type: 'set_fio2', fio2: 1.0 },
        { type: 'set_airway_device', device: 'ett' },
      ],
      highlight: ['airway-ett', 'fio2-slider'],
      teachingPoints: [
        'Dantrolene 2.5 mg/kg IV: inhibits RYR1 receptor → reduces SR calcium release → breaks muscle hypermetabolism.',
        'Dantrolene reconstitution: 20 mg per vial + 60 mL sterile water. For 200 mg: need 10 vials — requires team effort.',
        'MH hotline: 1-800-MH-HYPER — provides real-time dosing guidance.',
        'Repeat 2.5 mg/kg every 5 min until symptoms abate. Max 10 mg/kg.',
      ],
    },
    {
      id: 'step_mh_treatment',
      phase: 'complication',
      triggerType: 'on_step_complete',
      afterStepId: 'step_dantrolene',
      millieDialogue: [
        'Dantrolene given. What other cooling and metabolic interventions are needed?',
      ],
      question: {
        type: 'single_choice',
        prompt: 'Additional treatment measures for MH besides dantrolene?',
        options: [
          'Active cooling + bicarbonate for acidosis + treat arrhythmias + ICU admission',
          'Dantrolene is sufficient — no other treatment needed',
          'Succinylcholine to relax the muscles',
          'Propofol infusion to suppress temperature',
        ],
        correctAnswer: 'Active cooling + bicarbonate for acidosis + treat arrhythmias + ICU admission',
        feedback: {
          'Active cooling + bicarbonate for acidosis + treat arrhythmias + ICU admission': 'Correct! MH is a multi-system crisis requiring comprehensive treatment.',
          'Dantrolene is sufficient — no other treatment needed': 'Dantrolene addresses the primary cause but supportive treatment of complications is essential.',
          'Succinylcholine to relax the muscles': 'Succinylcholine can TRIGGER MH — absolutely contraindicated.',
          'Propofol infusion to suppress temperature': 'Propofol is not a temperature control agent and is safe to use but does not treat hyperthermia directly.',
        },
      },
      simActions: [
        { type: 'set_fio2', fio2: 1.0 },
      ],
      highlight: ['fio2-slider'],
      teachingPoints: [
        'MH comprehensive treatment: Dantrolene + active cooling + sodium bicarbonate 1-2 mEq/kg + treat VF/VT.',
        'Target core temperature <38.5°C. Stop cooling at 38°C — avoid overcorrection.',
        'ICU admission for 24-48 hours — late MH recurrence can occur.',
        'Test patient and family for RYR1 mutation — referral to MH testing center.',
      ],
    },
  ],
  debrief: {
    discussionQuestions: [
      'What would you tell this patient and his family after this MH event?',
      'How does MH differ from serotonin syndrome and neuroleptic malignant syndrome?',
      'What anesthetic technique would you use for this patient\'s future surgeries?',
    ],
    keyTakeaways: [
      'MH: hyperthermia + rigidity + tachycardia + rising EtCO2 = dantrolene + cooling + call MH hotline.',
      'Dantrolene 2.5 mg/kg IV: repeat every 5 min to max 10 mg/kg.',
      'Succinylcholine is absolutely contraindicated in MH susceptible patients.',
      'Future anesthesia: total IV anesthesia (TIVA) with propofol + opioid only — no volatile agents.',
    ],
  },
  scoringRubric: EXPERT_RUBRIC,
};

export const EXPERT_CARDIAC_ARREST: InteractiveScenario = {
  id: 'expert_cardiac_arrest',
  title: 'Cardiac Arrest During Sedation - VFib in HCM Patient',
  difficulty: 'expert',
  patientArchetype: 'hcm_old',
  procedure: 'Third Molar Surgery',
  description: 'Elderly patient with hypertrophic cardiomyopathy (HCM) and known VT history develops ventricular fibrillation during routine third molar surgery under sedation. Requires immediate ACLS.',
  learningObjectives: [
    'Recognize ventricular fibrillation from the ECG during sedation',
    'Apply ACLS high-quality CPR and defibrillation immediately',
    'Understand how HCM creates substrate for VF during sedation',
    'Manage post-ROSC care in the sedation setting',
  ],
  clinicalPearls: [
    'HCM: dynamic LVOT obstruction worsened by tachycardia, vasodilation (propofol), and reduced preload',
    'Sedation for HCM: maintain heart rate (not too fast, not too slow), volume loading, avoid vasodilators',
    'VFib management: CPR + shock within 2 minutes = 70%+ survival. Every minute without shock: -10% survival.',
    'Post-ROSC: targeted temperature management, ECHO to assess function, cardiac catheterization consideration',
  ],
  preopVignette: {
    indication: 'Third molar extraction under IV sedation — patient refused GA',
    setting: 'Oral surgery suite with AED available',
    history: [
      '70-year-old male, HCM (septal hypertrophy 22mm on echo)',
      'Known non-sustained VT on Holter, on amiodarone and metoprolol',
      'ASA 3 — compensated HCM, no syncope',
      'Cardiologist cleared for sedation with specific recommendations',
    ],
    exam: [
      'Airway: Mallampati 2',
      'HR 58 (beta-blocked), BP 128/82, SpO2 98%',
      'Soft systolic murmur at LLSB — dynamic obstruction',
    ],
    labs: ['Echo: EF 70%, septal thickness 22mm, mild LVOT gradient 18mmHg at rest'],
    baselineMonitors: ['Continuous 12-lead ECG capability', 'SpO2', 'Arterial line (recommended)', 'NIBP q3min', 'AED/defibrillator at bedside'],
    targetSedationGoal: 'MOASS 3-4 ONLY — avoid deep sedation in HCM. No propofol alone.',
  },
  drugProtocols: [
    { name: 'midazolam', route: 'IV', typicalBolusRange: [0.5, 1], maxTotalDose: 3, unit: 'mg' },
    { name: 'fentanyl', route: 'IV', typicalBolusRange: [25, 50], maxTotalDose: 100, unit: 'mcg' },
    { name: 'ketamine', route: 'IV', typicalBolusRange: [20, 40], maxTotalDose: 100, unit: 'mg' },
  ],
  steps: [
    {
      id: 'step_hcm_physiology',
      phase: 'pre_induction',
      triggerType: 'on_start',
      millieDialogue: [
        "This HCM patient has a dynamic LVOT obstruction. His cardiologist said 'avoid vasodilators and tachycardia'.",
        'Why is propofol potentially dangerous in HCM?',
      ],
      question: {
        type: 'single_choice',
        prompt: 'Why is propofol potentially hazardous in HCM with LVOT obstruction?',
        options: [
          'Propofol vasodilation reduces preload and afterload → worsens LVOT obstruction → cardiovascular collapse',
          'Propofol is arrhythmogenic in HCM',
          'Propofol causes bradycardia, worsening heart block',
          'Propofol increases LVOT gradient by stimulating myocardial contraction',
        ],
        correctAnswer: 'Propofol vasodilation reduces preload and afterload → worsens LVOT obstruction → cardiovascular collapse',
        feedback: {
          'Propofol vasodilation reduces preload and afterload → worsens LVOT obstruction → cardiovascular collapse': 'Correct! HCM LVOT obstruction worsens with reduced preload/afterload — propofol vasodilation is catastrophic.',
          'Propofol is arrhythmogenic in HCM': 'While arrhythmias can occur, the primary danger is hemodynamic from vasodilation and preload reduction.',
          'Propofol causes bradycardia, worsening heart block': 'Propofol can cause mild bradycardia but this is not the primary HCM risk.',
          'Propofol increases LVOT gradient by stimulating myocardial contraction': 'Propofol is a myocardial depressant, not a stimulant.',
        },
      },
      simActions: [
        { type: 'set_airway_device', device: 'nasal_cannula' },
        { type: 'set_fio2', fio2: 0.32 },
        { type: 'administer_drug', drug: 'midazolam', dose: 1 },
        { type: 'administer_drug', drug: 'fentanyl', dose: 25 },
        { type: 'advance_time', seconds: 90 },
      ],
      highlight: ['airway-nasal_cannula', 'fio2-slider', 'midazolam-1', 'fentanyl-25'],
      teachingPoints: [
        'HCM sedation principles: maintain preload (IV fluids), maintain afterload (avoid vasodilators), control HR (neither too fast nor too slow).',
        'Safe HCM sedation: midazolam + fentanyl only, or ketamine (maintains sympathetic tone).',
        'Pre-load with 250-500 mL NS before sedation.',
      ],
    },
    {
      id: 'step_vfib_recognition',
      phase: 'complication',
      triggerType: 'on_time',
      triggerTimeSeconds: 180,
      millieDialogue: [
        'Suddenly, the ECG alarm sounds — chaotic disorganized waveform, no recognizable QRS.',
        'SpO2 probe falls off. The oral surgeon turns to you in panic.',
        'What rhythm is this and what do you do FIRST?',
      ],
      question: {
        type: 'single_choice',
        prompt: 'Chaotic ECG without recognizable QRS — FIRST action?',
        options: [
          'Confirm pulselessness, call for help, start CPR immediately',
          'Wait 30 seconds for spontaneous conversion',
          'Give amiodarone 300 mg IV immediately',
          'Increase O2 and see if rhythm converts',
        ],
        correctAnswer: 'Confirm pulselessness, call for help, start CPR immediately',
        feedback: {
          'Confirm pulselessness, call for help, start CPR immediately': 'Correct! VFib = no pulse = start CPR + call for help + get defibrillator. Every second counts.',
          'Wait 30 seconds for spontaneous conversion': 'VFib does not self-terminate — waiting kills neurons. Start CPR immediately.',
          'Give amiodarone 300 mg IV immediately': 'Amiodarone is given AFTER the first shock — start CPR and defibrillation first.',
          'Increase O2 and see if rhythm converts': 'VFib is a cardiac arrest — O2 alone will not convert it.',
        },
      },
      simActions: [
        { type: 'apply_intervention', intervention: 'bag_mask' },
        { type: 'set_fio2', fio2: 1.0 },
      ],
      highlight: ['hr-display', 'fio2-slider'],
      teachingPoints: [
        'VFib recognition: chaotic, irregularly irregular ECG with no organized QRS complex.',
        'CPR first: rate 100-120/min, depth ≥2 inches, minimize interruptions.',
        'Time to first shock: every 1 minute delay reduces survival by ~10%.',
      ],
    },
    {
      id: 'step_defibrillation',
      phase: 'complication',
      triggerType: 'on_step_complete',
      afterStepId: 'step_vfib_recognition',
      millieDialogue: [
        'CPR is ongoing. The AED is ready. What is the correct defibrillation dose?',
      ],
      question: {
        type: 'single_choice',
        prompt: 'Correct defibrillation energy for VFib with biphasic defibrillator?',
        options: [
          '200 J biphasic (or maximum for device) — shock immediately',
          '50 J — start low, titrate up',
          '360 J monophasic equivalent first',
          '100 J initially, then 200 J if unsuccessful',
        ],
        correctAnswer: '200 J biphasic (or maximum for device) — shock immediately',
        feedback: {
          '200 J biphasic (or maximum for device) — shock immediately': 'Correct! AHA 2020: biphasic 200 J (or device maximum). Monophasic: 360 J.',
          '50 J — start low, titrate up': 'Sub-therapeutic dose wastes time — start at 200 J for VFib.',
          '360 J monophasic equivalent first': '360 J is correct for monophasic only — modern biphasic defibrillators are more efficient at 200 J.',
          '100 J initially, then 200 J if unsuccessful': 'No evidence for escalating protocol — start at 200 J for VFib.',
        },
      },
      simActions: [
        { type: 'set_fio2', fio2: 1.0 },
        { type: 'apply_intervention', intervention: 'bag_mask' },
      ],
      highlight: ['fio2-slider'],
      teachingPoints: [
        'Defibrillation: 200 J biphasic first. Resume CPR immediately after shock — do not wait to check pulse.',
        'Post-shock rhythm check: 2 minutes of CPR before rhythm check.',
        'Epinephrine 1 mg IV every 3-5 minutes after first shock.',
      ],
    },
    {
      id: 'step_post_rosc',
      phase: 'recovery',
      triggerType: 'on_time',
      triggerTimeSeconds: 420,
      millieDialogue: [
        'After 2 shocks and 4 minutes of CPR, ROSC achieved! HR 68, BP 102/66.',
        'What are the immediate post-ROSC priorities?',
      ],
      question: {
        type: 'single_choice',
        prompt: 'Immediate post-ROSC priorities after VFib in HCM?',
        options: [
          '12-lead ECG, airway secured, transfer to ICU for targeted temperature management + cardiology',
          'Discharge home after 30 minutes observation',
          'Resume the dental procedure immediately',
          'Give full amiodarone infusion and monitor in this room',
        ],
        correctAnswer: '12-lead ECG, airway secured, transfer to ICU for targeted temperature management + cardiology',
        feedback: {
          '12-lead ECG, airway secured, transfer to ICU for targeted temperature management + cardiology': 'Correct! All post-VFib ROSC patients need ICU level care, ECG, and cardiology involvement.',
          'Discharge home after 30 minutes observation': 'Absolutely not — post-VFib patients require ICU admission.',
          'Resume the dental procedure immediately': 'No procedure after cardiac arrest in a dental suite.',
          'Give full amiodarone infusion and monitor in this room': 'Amiodarone is appropriate but ICU transfer is mandatory — cannot manage post-arrest in a dental suite.',
        },
      },
      simActions: [
        { type: 'set_airway_device', device: 'ett' },
        { type: 'set_fio2', fio2: 1.0 },
      ],
      highlight: ['airway-ett', 'fio2-slider'],
      teachingPoints: [
        'Post-ROSC: 12-lead ECG to assess for STEMI (PCI indication), secure airway, transfer to ICU.',
        'Targeted temperature management: 32-36°C for 24 hours if comatose post-ROSC.',
        'Cardiology: evaluate for ICD implantation in HCM with VFib arrest.',
        'Document everything: times, interventions, drug doses — legal and quality improvement.',
      ],
    },
  ],
  debrief: {
    discussionQuestions: [
      'What is the acceptable minimum response time to first defibrillation in an outpatient sedation suite?',
      'How does HCM pathophysiology create the substrate for VFib?',
      'What sedation technique would you use for future procedures in this patient?',
    ],
    keyTakeaways: [
      'HCM + sedation: maintain preload/afterload, avoid propofol vasodilation, use ketamine or midazolam.',
      'VFib: confirm pulselessness, CPR immediately, shock at 200 J biphasic, resume CPR after shock.',
      'AED should be present within 3 minutes of ANY procedure room with sedation.',
      'All post-VFib ROSC patients: ICU, 12-lead ECG, cardiology, consider TTM.',
    ],
  },
  scoringRubric: EXPERT_RUBRIC,
};

export const EXPERT_CHF_SEDATION: InteractiveScenario = {
  id: 'chf_sedation_challenge',
  title: 'Sedation in Congestive Heart Failure',
  difficulty: 'expert',
  patientArchetype: 'chf_nyha3',
  procedure: 'Procedural Sedation — GI Endoscopy',
  description: 'A challenging case requiring careful sedation management in a patient with NYHA Class III congestive heart failure. Reduced cardiac output, pulmonary congestion, and hepatic hypoperfusion demand significant dose reduction and vigilant monitoring.',
  learningObjectives: [
    'Understand how reduced cardiac output alters pharmacokinetics of propofol and fentanyl',
    'Apply appropriate dose reductions for high-extraction drugs in CHF',
    'Recognize and manage sedation-induced hypotension in CHF patients',
    'Interpret the significance of baseline SpO2 of 94% and its proximity to the desaturation cliff',
    'Identify signs of pulmonary congestion worsening during procedural sedation',
    'Understand atrial fibrillation risk and rhythm monitoring in CHF sedation',
  ],
  clinicalPearls: [
    'Reduce all sedative and opioid doses by 50% in NYHA III-IV CHF; titrate slowly with extended intervals',
    'Fentanyl and propofol are high-hepatic-extraction drugs; CHF reduces hepatic blood flow, dramatically increasing plasma levels per dose',
    'Baseline SpO2 of 94% indicates the patient is near the steep portion of the O2-Hb dissociation curve — desaturation is rapid with any hypoventilation',
    'The CHF baroreflex is blunted: propofol-induced vasodilation is poorly compensated, making hypotension more severe and prolonged',
    'Atrial fibrillation risk is elevated in CHF; avoid triggers including hypoxia, hypercarbia, pain, and tachycardia',
    'Pre-oxygenation to SpO2 ≥98% is mandatory before any sedation in CHF patients',
    'Phenylephrine is preferred over ephedrine for sedation-related hypotension in CHF to avoid worsening tachycardia',
    'EtCO2 monitoring provides earlier warning of hypoventilation than pulse oximetry — mandatory in this population',
  ],
  preopVignette: {
    indication: 'Elective upper endoscopy for iron-deficiency anemia workup',
    setting: 'Outpatient endoscopy suite',
    history: [
      '68-year-old male, ASA 4, NYHA Class III CHF',
      'Ischemic cardiomyopathy, EF 30%, on carvedilol, lisinopril, furosemide, spironolactone',
      'Atrial fibrillation (rate-controlled), on warfarin (INR 2.1)',
      'Baseline: dyspnea on minimal exertion, bilateral ankle edema',
    ],
    exam: [
      'HR 87 (compensatory tachycardia), BP 100/70, SpO2 94% on room air',
      'Mild JVD, bibasilar crackles on auscultation',
      'Airway: Mallampati 2, adequate neck extension',
    ],
    labs: [
      'Hgb 9.2 g/dL (iron-deficiency anemia)',
      'BNP 620 pg/mL (elevated, compensated CHF)',
      'Creatinine 1.6 mg/dL (cardiorenal syndrome)',
    ],
    baselineMonitors: ['SpO2', 'EtCO2', 'NIBP q3min', 'Continuous ECG'],
    targetSedationGoal: 'Minimal to moderate sedation (MOASS 2-3); avoid deep sedation',
  },
  drugProtocols: [
    { name: 'midazolam', route: 'IV', typicalBolusRange: [0.5, 0.5], maxTotalDose: 1, unit: 'mg' },
    { name: 'fentanyl', route: 'IV', typicalBolusRange: [25, 25], maxTotalDose: 50, unit: 'mcg' },
    { name: 'propofol', route: 'IV', typicalBolusRange: [10, 20], maxTotalDose: 50, unit: 'mg' },
    { name: 'phenylephrine', route: 'IV', typicalBolusRange: [50, 100], maxTotalDose: 300, unit: 'mcg' },
  ],
  steps: [
    {
      id: 'step_initial_assessment',
      phase: 'pre_induction',
      triggerType: 'on_start',
      millieDialogue: [
        'Meet our patient: a 68-year-old male with NYHA Class III CHF, EF 30%, and atrial fibrillation.',
        'HR 87, BP 100/70, SpO2 94% on room air. BNP 620. He is compensated but on the edge.',
        'What is your FIRST priority before giving any sedation?',
      ],
      voiceText: 'This sixty-eight year old male has NYHA Class III heart failure. Notice his compensatory tachycardia at eighty-seven beats per minute, his blood pressure is already reduced at one hundred over seventy, and his resting SpO2 is only ninety-four percent on room air. He is on the steep portion of the oxygen-hemoglobin dissociation curve. Any further respiratory depression will cause rapid desaturation.',
      question: {
        type: 'single_choice',
        prompt: 'Before administering any sedative, what is the most important first step?',
        options: [
          'Start supplemental oxygen to increase SpO2 to ≥98%',
          'Give midazolam 1mg IV immediately',
          'Request general anesthesia consultation',
          'Check INR before proceeding',
        ],
        correctAnswer: 'Start supplemental oxygen to increase SpO2 to ≥98%',
        feedback: {
          'Start supplemental oxygen to increase SpO2 to ≥98%': 'Correct! Pre-oxygenation is mandatory. Baseline SpO2 94% means we must build oxygen reserve before any drug that could impair ventilation.',
          'Give midazolam 1mg IV immediately': 'Never start sedation with SpO2 94% without pre-oxygenation. Any respiratory depression could cause rapid desaturation.',
          'Request general anesthesia consultation': 'This patient can be sedated safely with appropriate precautions — pre-oxygenation comes first.',
          'Check INR before proceeding': 'INR should already be known pre-procedure, but optimizing oxygenation is the immediate priority.',
        },
      },
      simActions: [
        { type: 'select_patient', archetypeKey: 'chf_nyha3' },
        { type: 'set_airway_device', device: 'nasal_cannula' },
      ],
      highlight: ['patient-info', 'vitals'],
      teachingPoints: [
        'Baseline SpO2 94% = patient is near the steep portion of the O2-Hb dissociation curve.',
        'Pre-oxygenation to SpO2 ≥98% is mandatory in CHF before any sedation.',
      ],
    },
    {
      id: 'step_preoxygenation',
      phase: 'pre_induction',
      triggerType: 'on_time',
      triggerTimeSeconds: 15,
      millieDialogue: [
        'Good — supplemental oxygen applied via nasal cannula at FiO2 40%.',
        'SpO2 is now climbing toward 98%. We are building our oxygen reserve.',
        'How long should we pre-oxygenate before giving the first drug?',
      ],
      voiceText: 'Increase FiO2 to forty percent via nasal cannula. This patient starts at ninety-four percent. We want to push him to at least ninety-eight percent before we give anything that could impair ventilation. We are buying time on that oxygen-hemoglobin curve.',
      question: {
        type: 'single_choice',
        prompt: 'How long should you pre-oxygenate this CHF patient before first drug administration?',
        options: [
          'At least 2-3 minutes until SpO2 ≥98%',
          '30 seconds is sufficient',
          'Pre-oxygenation is unnecessary if using low-dose midazolam',
          '10 minutes of 100% FiO2 via face mask',
        ],
        correctAnswer: 'At least 2-3 minutes until SpO2 ≥98%',
        feedback: {
          'At least 2-3 minutes until SpO2 ≥98%': 'Correct! Allow adequate time for SpO2 to reach ≥98% before any sedation. This maximizes oxygen reserve.',
          '30 seconds is sufficient': 'Thirty seconds is not enough to meaningfully increase oxygen stores, especially with CHF reducing FRC.',
          'Pre-oxygenation is unnecessary if using low-dose midazolam': 'Even low-dose midazolam can cause significant respiratory depression in this CHF patient.',
          '10 minutes of 100% FiO2 via face mask': 'This is excessive for a spontaneously breathing patient and 100% FiO2 via nasal cannula is impractical — 40-44% via nasal cannula at 4-6 L/min is appropriate.',
        },
      },
      simActions: [
        { type: 'set_fio2', fio2: 0.40 },
        { type: 'advance_time', seconds: 120 },
      ],
      highlight: ['interventions-panel'],
      teachingPoints: [
        'CHF reduces functional residual capacity — oxygen stores are already diminished.',
        'Target SpO2 ≥98% before any sedation agent in CHF.',
      ],
    },
    {
      id: 'step_midazolam',
      phase: 'induction',
      triggerType: 'on_time',
      triggerTimeSeconds: 45,
      millieDialogue: [
        'SpO2 is now 98%. Patient is calm. Time to begin sedation.',
        'You reach for midazolam. Standard dose is 1-2mg IV.',
        'What dose should you use in this NYHA III CHF patient?',
      ],
      voiceText: 'We are giving only half a milligram of midazolam, one quarter of a standard dose. In heart failure, hepatic blood flow is reduced proportionally to cardiac output reduction. Midazolam is extensively hepatically metabolized, so its half-life can double or triple in CHF. Small doses accumulate to large effects.',
      question: {
        type: 'single_choice',
        prompt: 'What is the appropriate midazolam dose for this NYHA III CHF patient?',
        options: [
          '0.5mg IV — 50% dose reduction due to reduced hepatic clearance',
          '1mg IV — standard starting dose',
          '2mg IV — he weighs 85kg so a larger dose is appropriate',
          '0.1mg/kg IV — weight-based dosing is always correct',
        ],
        correctAnswer: '0.5mg IV — 50% dose reduction due to reduced hepatic clearance',
        feedback: {
          '0.5mg IV — 50% dose reduction due to reduced hepatic clearance': 'Correct! CHF reduces hepatic blood flow, doubling or tripling midazolam half-life. Start with 0.5mg and wait before considering redosing.',
          '1mg IV — standard starting dose': 'Standard dosing in CHF will result in significantly elevated plasma concentrations and prolonged effect.',
          '2mg IV — he weighs 85kg so a larger dose is appropriate': 'Weight-based standard dosing is inappropriate here. The reduced clearance, not weight, drives the need for dose reduction.',
          '0.1mg/kg IV — weight-based dosing is always correct': 'Weight-based standard dosing is dangerous in CHF. Organ dysfunction trumps weight-based calculations.',
        },
      },
      simActions: [
        { type: 'administer_drug', drug: 'midazolam', dose: 0.5 },
        { type: 'advance_time', seconds: 90 },
      ],
      highlight: ['midazolam-panel'],
      teachingPoints: [
        'Midazolam is CYP3A4 and hepatically metabolized — CHF reduces hepatic blood flow, prolonging half-life 2-3x.',
        'Always reduce benzodiazepine doses by 50% or more in NYHA III-IV CHF.',
        'Wait 90-120 seconds (not 60) before assessing midazolam effect in CHF — slower distribution.',
      ],
    },
    {
      id: 'step_extended_wait',
      phase: 'induction',
      triggerType: 'on_time',
      triggerTimeSeconds: 120,
      millieDialogue: [
        'You have given 0.5mg midazolam. Now you wait.',
        'The endoscopist asks: "Is he sedated yet? Can I start?"',
        'How long should you wait before assessing effect and considering additional drugs?',
      ],
      voiceText: 'We wait ninety seconds, not the usual sixty. Reduced cardiac output means slower distribution. The drug takes longer to reach the effect site. Watch the pharmacokinetic curves — the effect-site concentration is rising more slowly than you would see in a healthy patient. Do not be tempted to redose prematurely.',
      question: {
        type: 'single_choice',
        prompt: 'After midazolam 0.5mg IV in a CHF patient, when should you assess effect before giving more drug?',
        options: [
          'Wait 90-120 seconds — reduced CO slows drug distribution to effect site',
          'Wait 30 seconds — midazolam acts quickly',
          'Give fentanyl immediately without waiting for midazolam effect',
          'Check MOASS at 60 seconds just like any other patient',
        ],
        correctAnswer: 'Wait 90-120 seconds — reduced CO slows drug distribution to effect site',
        feedback: {
          'Wait 90-120 seconds — reduced CO slows drug distribution to effect site': 'Correct! Reduced cardiac output means slower drug delivery to the effect site (brain). The peak effect takes longer — stacking doses leads to overshoot.',
          'Wait 30 seconds — midazolam acts quickly': 'In healthy patients, onset is about 60-90 seconds. In CHF, distribution is slowed — 30 seconds is too early.',
          'Give fentanyl immediately without waiting for midazolam effect': 'Stacking drugs without assessing each one\'s effect is dangerous in CHF.',
          'Check MOASS at 60 seconds just like any other patient': 'CHF slows drug distribution — 60 seconds may not reflect peak effect. Wait longer.',
        },
      },
      simActions: [
        { type: 'advance_time', seconds: 90 },
      ],
      highlight: ['trend-graph'],
      teachingPoints: [
        'Reduced cardiac output = reduced drug delivery rate to effect site.',
        'Premature redosing before peak effect is the most common cause of oversedation in CHF.',
        'Observe pharmacokinetic trends — effect-site concentration rise is slower than in healthy patients.',
      ],
    },
    {
      id: 'step_fentanyl',
      phase: 'induction',
      triggerType: 'on_time',
      triggerTimeSeconds: 150,
      millieDialogue: [
        'Patient is calm, MOASS ~3. Time to add analgesia.',
        'Standard fentanyl starting dose is 50mcg IV.',
        'What dose is appropriate here?',
      ],
      voiceText: 'Twenty-five micrograms of fentanyl, half the usual starting dose. Fentanyl has very high hepatic extraction — its clearance is blood-flow dependent. With cardiac output reduced thirty to fifty percent, fentanyl clearance falls proportionally. We will see higher plasma concentrations per dose compared to a healthy patient.',
      question: {
        type: 'single_choice',
        prompt: 'What fentanyl dose is appropriate for this CHF patient?',
        options: [
          '25mcg IV — high-extraction drug with blood-flow dependent clearance',
          '50mcg IV — standard starting dose',
          '100mcg IV — he is a large male so needs a higher dose',
          '1mcg/kg — standard weight-based opioid dosing',
        ],
        correctAnswer: '25mcg IV — high-extraction drug with blood-flow dependent clearance',
        feedback: {
          '25mcg IV — high-extraction drug with blood-flow dependent clearance': 'Correct! Fentanyl is a high-hepatic-extraction drug — its clearance is proportional to hepatic blood flow. CHF reduces this by 30-50%, dramatically increasing plasma levels per dose.',
          '50mcg IV — standard starting dose': 'Standard dosing in CHF will produce approximately double the expected plasma concentration — risk of respiratory depression.',
          '100mcg IV — he is a large male so needs a higher dose': 'Body weight is irrelevant when organ clearance is significantly impaired. Use 25mcg and reassess.',
          '1mcg/kg — standard weight-based opioid dosing': 'Standard weight-based dosing ignores the critical pharmacokinetic alteration in CHF.',
        },
      },
      simActions: [
        { type: 'administer_drug', drug: 'fentanyl', dose: 25 },
        { type: 'advance_time', seconds: 60 },
      ],
      highlight: ['fentanyl-panel'],
      teachingPoints: [
        'Fentanyl: high extraction ratio (~0.9) — clearance is blood-flow limited.',
        'CHF reduces hepatic blood flow by 30-50% → fentanyl clearance reduced by same proportion.',
        'Plasma concentration per dose is 1.5-2x higher in CHF than in healthy patients.',
      ],
    },
    {
      id: 'step_propofol',
      phase: 'induction',
      triggerType: 'on_time',
      triggerTimeSeconds: 210,
      millieDialogue: [
        'Patient is at MOASS ~3. Procedure is about to start.',
        'The endoscopist requests a bit more sedation. You consider propofol.',
        'What is the appropriate starting dose of propofol in this patient?',
      ],
      voiceText: 'Ten milligrams of propofol — this is a micro-dose. Propofol is a potent vasodilator. In a healthy patient, the baroreflex compensates for the drop in afterload. But in CHF, the baroreflex is blunted, and the failing heart cannot increase output to maintain pressure. Even small doses of propofol can precipitate significant hypotension.',
      question: {
        type: 'single_choice',
        prompt: 'What propofol dose would you use to deepen sedation slightly in this CHF patient?',
        options: [
          '10mg IV micro-dose — vasodilation effect is poorly compensated in CHF',
          '40mg IV — standard induction bolus',
          '20mg IV — half the standard dose should be safe',
          'Avoid propofol entirely in CHF',
        ],
        correctAnswer: '10mg IV micro-dose — vasodilation effect is poorly compensated in CHF',
        feedback: {
          '10mg IV micro-dose — vasodilation effect is poorly compensated in CHF': 'Correct! Propofol causes vasodilation. In CHF, the baroreflex is blunted and cardiac output cannot increase to compensate. Even 10mg can cause meaningful hypotension.',
          '40mg IV — standard induction bolus': 'This dose will cause severe hypotension in a CHF patient with BP already at 100/70.',
          '20mg IV — half the standard dose should be safe': 'Even 20mg can precipitate significant hypotension in CHF. Start with 10mg and reassess.',
          'Avoid propofol entirely in CHF': 'Propofol can be used cautiously in micro-doses in CHF. It is not absolutely contraindicated.',
        },
      },
      simActions: [
        { type: 'administer_drug', drug: 'propofol', dose: 10 },
        { type: 'advance_time', seconds: 60 },
      ],
      highlight: ['propofol-panel'],
      teachingPoints: [
        'Propofol is a potent vasodilator — reduces preload and afterload.',
        'CHF blunts baroreflex: heart cannot compensate for vasodilation by increasing rate or contractility.',
        'Micro-dosing (10mg increments) is essential to avoid precipitous hypotension.',
      ],
    },
    {
      id: 'step_hypotension_monitoring',
      phase: 'maintenance',
      triggerType: 'on_time',
      triggerTimeSeconds: 270,
      millieDialogue: [
        'BP is now 88/52. MAP has dropped to 64 mmHg — just below our target of 65.',
        'HR remains 87 — no compensatory tachycardia occurred.',
        'What does this tell you about the CHF baroreflex?',
      ],
      voiceText: 'Watch the blood pressure carefully now. If mean arterial pressure falls below sixty-five, we have a problem. Unlike healthy patients, our CHF patient cannot rely on a strong baroreflex to compensate. Their sympathetic tone is already maximally activated — there is little reserve left. Have a vasopressor ready.',
      question: {
        type: 'single_choice',
        prompt: 'BP dropped to 88/52 after 10mg propofol with NO compensatory tachycardia. Why?',
        options: [
          'The CHF baroreflex is blunted — maximal sympathetic tone is already baseline',
          'The patient is in vasovagal syncope',
          'Propofol is a direct negative chronotrope',
          'The beta-blocker (carvedilol) is masking the tachycardia',
        ],
        correctAnswer: 'The CHF baroreflex is blunted — maximal sympathetic tone is already baseline',
        feedback: {
          'The CHF baroreflex is blunted — maximal sympathetic tone is already baseline': 'Correct! CHF patients have chronically elevated sympathetic tone as a compensation — the baroreflex cannot increase it further. HR 87 is already the compensatory response at baseline.',
          'The patient is in vasovagal syncope': 'Vasovagal requires a trigger (pain, anxiety) and causes bradycardia. This is pure vasodilation from propofol.',
          'Propofol is a direct negative chronotrope': 'Propofol can cause mild bradycardia but the primary mechanism here is vasodilation with impaired reflex tachycardia.',
          'The beta-blocker (carvedilol) is masking the tachycardia': 'Partially true — carvedilol does blunt tachycardic response — but the primary issue is the blunted CHF baroreflex.',
        },
      },
      simActions: [
        { type: 'advance_time', seconds: 30 },
      ],
      highlight: ['vitals', 'trend-graph'],
      teachingPoints: [
        'CHF baroreflex is chronically blunted — sympathetic tone is maximally activated at baseline.',
        'The compensatory tachycardia you expect in healthy patients often does not occur in CHF.',
        'Monitor MAP closely: target >65 mmHg. In CHF, hypotension is less compensated and more dangerous.',
      ],
    },
    {
      id: 'step_hypotension_treatment',
      phase: 'complication',
      triggerType: 'on_time',
      triggerTimeSeconds: 330,
      millieDialogue: [
        'MAP is 64. You need to act. The endoscopist asks you to continue.',
        'What is your preferred vasopressor for sedation-induced hypotension in this CHF/AF patient?',
      ],
      voiceText: 'If we see hypotension, our options are limited. A small crystalloid bolus of two-fifty milliliters can improve preload. Phenylephrine is our preferred vasopressor here, not ephedrine — we do not want to increase heart rate in this patient. The tachycardia already indicates significant sympathetic drive. Adding more with ephedrine risks precipitating atrial fibrillation.',
      question: {
        type: 'single_choice',
        prompt: 'For sedation-induced hypotension in this CHF + atrial fibrillation patient, which vasopressor is preferred?',
        options: [
          'Phenylephrine 100mcg IV — pure alpha-1 agonist, no tachycardia risk',
          'Ephedrine 10mg IV — increases BP and HR',
          'Epinephrine 100mcg IV — most potent option',
          'No vasopressor — just give 1L normal saline bolus',
        ],
        correctAnswer: 'Phenylephrine 100mcg IV — pure alpha-1 agonist, no tachycardia risk',
        feedback: {
          'Phenylephrine 100mcg IV — pure alpha-1 agonist, no tachycardia risk': 'Correct! Phenylephrine is a pure alpha-1 agonist — it increases SVR and MAP without increasing heart rate. This is ideal in CHF with AF where avoiding tachycardia is critical.',
          'Ephedrine 10mg IV — increases BP and HR': 'Ephedrine has alpha and beta agonist activity — the beta-1 stimulation increases HR, which can precipitate AF and worsen CHF by reducing diastolic filling time.',
          'Epinephrine 100mcg IV — most potent option': 'Epinephrine is too potent for this hemodynamic situation and will cause significant tachycardia and risk AF.',
          'No vasopressor — just give 1L normal saline bolus': 'A small crystalloid bolus (250mL) is reasonable, but CHF patients are already volume-overloaded — 1L is excessive and risks flash pulmonary edema.',
        },
      },
      simActions: [
        { type: 'administer_drug', drug: 'phenylephrine', dose: 100 },
        { type: 'advance_time', seconds: 60 },
      ],
      highlight: ['vitals', 'interventions-panel'],
      teachingPoints: [
        'Phenylephrine: pure alpha-1 agonist — increases MAP without increasing HR.',
        'Ephedrine is AVOIDED in CHF + AF — beta-1 activity increases HR and risk of AF.',
        'Small crystalloid bolus (250mL) may supplement vasopressor but avoid volume overload in CHF.',
      ],
    },
    {
      id: 'step_respiratory_vigilance',
      phase: 'maintenance',
      triggerType: 'on_time',
      triggerTimeSeconds: 420,
      millieDialogue: [
        'Hemodynamics are stabilized. Procedure is ongoing. EtCO2 is now 48 mmHg.',
        'SpO2 is 94% — back at baseline. Should you be concerned?',
      ],
      voiceText: 'This patient\'s pulmonary congestion means his oxygen reserve is minimal. Watch EtCO2 continuously — it will rise before SpO2 falls. If EtCO2 climbs above fifty, that tells us hypoventilation is occurring. We may need to provide jaw thrust or verbal stimulation. Avoid deepening sedation further unless absolutely necessary.',
      question: {
        type: 'single_choice',
        prompt: 'EtCO2 48 mmHg and SpO2 back to 94% (baseline). What is your interpretation?',
        options: [
          'EtCO2 trending up suggests early hypoventilation — intervene before SpO2 falls further',
          'SpO2 94% is his baseline — no concern, he is fine',
          'Increase FiO2 to treat the low SpO2',
          'Deepen sedation — he is moving',
        ],
        correctAnswer: 'EtCO2 trending up suggests early hypoventilation — intervene before SpO2 falls further',
        feedback: {
          'EtCO2 trending up suggests early hypoventilation — intervene before SpO2 falls further': 'Correct! Rising EtCO2 (especially toward 50+) indicates hypoventilation. In this patient with pulmonary congestion, SpO2 will fall rapidly once EtCO2 exceeds 50. Intervene now with jaw thrust, verbal stimulation, or temporary reduction in sedation.',
          'SpO2 94% is his baseline — no concern, he is fine': 'Dangerous reasoning. SpO2 may be at baseline, but rising EtCO2 signals hypoventilation — SpO2 will drop rapidly in this patient. Act before it falls.',
          'Increase FiO2 to treat the low SpO2': 'Increasing FiO2 treats oxygenation but does not address the hypoventilation. EtCO2 monitoring identifies ventilation problems — oxygen alone is not the answer.',
          'Deepen sedation — he is moving': 'Deepening sedation when EtCO2 is rising will worsen hypoventilation and risk rapid desaturation. This is the wrong direction.',
        },
      },
      simActions: [
        { type: 'advance_time', seconds: 60 },
      ],
      highlight: ['vitals', 'trend-graph'],
      teachingPoints: [
        'EtCO2 is the earliest warning of hypoventilation — acts before SpO2 falls.',
        'In CHF with pulmonary congestion, the desaturation cliff is steep — act early.',
        'Jaw thrust, verbal stimulation, and brief sedation reduction are first-line interventions.',
      ],
    },
    {
      id: 'step_rhythm_monitoring',
      phase: 'maintenance',
      triggerType: 'on_time',
      triggerTimeSeconds: 540,
      millieDialogue: [
        'The ECG monitor shows an irregular rhythm. The patient has a known history of AF.',
        'Rate is now 110 bpm — faster than at baseline.',
        'What is your concern and what should you check immediately?',
      ],
      voiceText: 'Keep a close eye on the cardiac rhythm. CHF patients with dilated, hypertrophied, or fibrotic atria are susceptible to atrial fibrillation. Hypoxia, hypercarbia, or sympathetic stimulation from pain or light sedation can trigger AF. If the rhythm becomes irregular, verify it is not AF and assess hemodynamic impact.',
      question: {
        type: 'single_choice',
        prompt: 'Irregular rhythm at 110 bpm in a CHF patient who had rate-controlled AF at baseline. What is your first action?',
        options: [
          'Verify rhythm on ECG and assess hemodynamics — rule out rapid ventricular response AF',
          'Give adenosine immediately to break the rhythm',
          'This is normal — the AF rate always fluctuates',
          'Start amiodarone infusion for cardioversion',
        ],
        correctAnswer: 'Verify rhythm on ECG and assess hemodynamics — rule out rapid ventricular response AF',
        feedback: {
          'Verify rhythm on ECG and assess hemodynamics — rule out rapid ventricular response AF': 'Correct! First, confirm the rhythm and assess hemodynamic impact. If AF with rapid ventricular response is causing hemodynamic compromise, rate control with IV metoprolol or diltiazem may be needed.',
          'Give adenosine immediately to break the rhythm': 'Adenosine is for SVT (AVNRT/AVRT), not AF. Using adenosine for AF will not cardiovert — it temporarily blocks the AV node.',
          'This is normal — the AF rate always fluctuates': 'A jump from 87 to 110 bpm in a patient with poorly compensated CHF is clinically significant. Rate-controlled AF can become poorly rate-controlled under sedation-related stress.',
          'Start amiodarone infusion for cardioversion': 'Cardioversion (pharmacologic or electrical) during active endoscopy with anticoagulation is not immediately indicated. First assess hemodynamics and rate control.',
        },
      },
      simActions: [
        { type: 'advance_time', seconds: 60 },
      ],
      highlight: ['vitals', 'monitor-panel'],
      teachingPoints: [
        'CHF + AF: hypoxia and hypercarbia are common triggers for rapid ventricular response during sedation.',
        'Rate-controlled AF can become poorly rate-controlled under sedation stress.',
        'Verify rhythm, assess hemodynamics, treat precipitants (hypoxia, pain) before pharmacologic rate control.',
      ],
    },
    {
      id: 'step_emergence',
      phase: 'recovery',
      triggerType: 'on_time',
      triggerTimeSeconds: 660,
      millieDialogue: [
        'Procedure complete. Sedation is wearing off. The patient is beginning to stir.',
        'SpO2 is 95%, HR 90, BP 102/68.',
        'When is it safe to discharge this patient from monitoring?',
      ],
      voiceText: 'As we emerge from sedation, remember that drug effects will linger longer than expected. Fentanyl and midazolam accumulate with repeated dosing in CHF. Do not rush discharge. Ensure SpO2 has returned to at least the patient\'s baseline of ninety-four percent, that mental status is appropriate, and that hemodynamics are stable before releasing them from monitoring.',
      question: {
        type: 'single_choice',
        prompt: 'What minimum criteria must be met before discharging this CHF patient from post-procedure monitoring?',
        options: [
          'SpO2 ≥94% (baseline), hemodynamically stable, alert and oriented, no respiratory distress',
          'SpO2 >90% and patient is awake',
          'MOASS 5 (fully awake) within 30 minutes of last drug',
          'BP >120/80 and HR <60',
        ],
        correctAnswer: 'SpO2 ≥94% (baseline), hemodynamically stable, alert and oriented, no respiratory distress',
        feedback: {
          'SpO2 ≥94% (baseline), hemodynamically stable, alert and oriented, no respiratory distress': 'Correct! Discharge criteria must be individualized to the patient\'s baseline. SpO2 returning to at least the pre-procedure baseline (94%) is the target, not a generic 95%.',
          'SpO2 >90% and patient is awake': 'SpO2 90% is below this patient\'s baseline of 94% — this would represent deterioration from pre-procedure status.',
          'MOASS 5 (fully awake) within 30 minutes of last drug': 'Drugs linger longer in CHF. MOASS 5 is a good target but does not alone ensure safe discharge — hemodynamics and SpO2 baseline must also be met.',
          'BP >120/80 and HR <60': 'These vital sign targets are inappropriate for this patient whose baseline is BP 100/70, HR 87.',
        },
      },
      simActions: [
        { type: 'advance_time', seconds: 60 },
      ],
      highlight: ['vitals', 'event-log'],
      teachingPoints: [
        'CHF prolongs drug clearance — fentanyl and midazolam effects last longer than expected.',
        'Discharge criteria must be individualized to patient baseline, not generic population norms.',
        'SpO2 must return to at least pre-procedure baseline before discharge.',
      ],
    },
  ],
  debrief: {
    discussionQuestions: [
      'How does NYHA Class III vs. Class IV CHF change your sedation approach?',
      'At what point would you have converted this case to general anesthesia?',
      'How would you modify this protocol if the patient had severe renal failure in addition to CHF?',
      'What are the pros and cons of dexmedetomidine as the primary sedation agent in CHF patients?',
    ],
    keyTakeaways: [
      'CHF demands 50% dose reduction of all sedatives and opioids — titrate slowly with extended waiting intervals.',
      'Pre-oxygenation to SpO2 ≥98% before any drug is mandatory in CHF.',
      'Phenylephrine over ephedrine for hypotension management in CHF — avoid beta-1 stimulation.',
      'EtCO2 is the earliest ventilation warning — monitor continuously and act before SpO2 falls.',
    ],
  },
  scoringRubric: EXPERT_RUBRIC,
};

export const EXPERT_SCENARIOS: InteractiveScenario[] = [
  EXPERT_PRIS,
  EXPERT_MULTI_DRUG,
  EXPERT_AWARENESS,
  EXPERT_MALIGNANT_HYPERTHERMIA,
  EXPERT_CARDIAC_ARREST,
  EXPERT_CHF_SEDATION,
];
